name: Build NetDebugHost .deb Packages

on:
  push:
    branches: [ master ]
  pull_request:

env:
  VERSION: "1.0.0"  # 可修改为读取 git tag，例如用 release/tag 触发

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    name: Build for ${{ matrix.arch }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake ninja-build \
            libudev-dev libnm-dev libwpa-client-dev \
            python3-pip \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install xrobot and run xrobot_setup
        run: |
          pip install --upgrade pip
          pip install xrobot
          xrobot_setup

      - name: Configure and build project
        run: |
          mkdir -p build
          cd build
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            cmake .. -GNinja \
              -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
              -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
              -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          else
            cmake .. -GNinja
          fi
          cmake --build . --target NetDebugHost

      - name: Package .deb
        run: |
          VERSION=${{ env.VERSION }} ARCH=${{ matrix.arch }} ./build_deb.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: netdebughost-${{ matrix.arch }}
          path: NetDebugHost_*.deb
