name: Build NetDebugHost .deb Packages

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    name: Build for ${{ matrix.arch }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU (for arm64)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build in XRobot Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/xrobot-org/docker-image-linux:main
          options: |
            --privileged
            --platform linux/${{ matrix.arch }}
            -v ${{ github.workspace }}:/workspace
            -w /workspace
          run: |
            set -e

            echo "==> 1. 安装 Python 工具链"
            pip install --upgrade pip
            pip install xrobot

            echo "==> 2. 运行 xrobot_setup"
            xrobot_setup

            echo "==> 3. 构建项目 (${ARCH})"
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make -j$(nproc)

            echo "==> 4. 打包 .deb (${ARCH})"
            cd ..
            ARCH=${{ matrix.arch }} ./build_deb.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: netdebughost-${{ matrix.arch }}
          path: NetDebugHost_1.0.0.deb
